### PR TITLE
update release.md

### PR DESCRIPTION
**Pull request by puneet-pdx**

### CODE REVIEW

**Comment by puneet-pdx** [comment]
@esreli please review

**Review by esreli — COMMENTED** [review]
It appears the App Version name is `1.0.8`. Can you modify this to match the version name for this release, `1.0.7`?

Screen Shot 2020-09-03 at 3 53 43 PM

**Comment by puneet-pdx** [comment]
@esreli good catch. Updated.

**Review by esreli — APPROVED** [review]
LGTM 👍

**Pull request merged**
